//
//  PullRequestsListModels.swift
//  GithubRepositories
//
//  Created by Junior Silva on 21/07/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PullRequestsList {
    
    struct RequestList: Codable {
        let author: Owner
        let title: String
        let date: String
        let body: String?
        
        enum CodingKeys: String, CodingKey {
            case author = "user"
            case title
            case date = "created_at"
            case body
        }
    }
    
    struct ViewModel {
        var title: String
        var body: String?
        var author: String
        var authorImage: String
        var date: String
        
        init(pullRequest: RequestList) {
            title = pullRequest.title
            body = pullRequest.body
            author = pullRequest.author.name
            authorImage = pullRequest.author.avatar
            date = pullRequest.date
        }
    }
    
}
