//
//  PullRequestsListInteractor.swift
//  GithubRepositories
//
//  Created by Junior Silva on 21/07/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol PullRequestsListBusinessLogic {
    func fetchPullRequestsList()
}

protocol PullRequestsListDataStore {
    var repository: Repository? { get set }
}

class PullRequestsListInteractor: PullRequestsListBusinessLogic, PullRequestsListDataStore {
    var presenter: PullRequestsListPresentationLogic?
    var worker: PullRequestsListWorker?
    
    var repository: Repository?
    
    init(worker: PullRequestsListWorker = PullRequestsListWorker()) {
        self.worker = worker
    }
    
    func fetchPullRequestsList() {
        guard let selectedRepository = repository else { return }
        worker?.searchPullRequestsList(selectedRepository).done(handleSuccess).catch(handleError)
    }
    
    private func handleSuccess(_ response: [PullRequestsList.RequestList]) {
        print(response)
    }
    
    private func handleError(_ error: Error) {
        print(error.localizedDescription)
    }
    
}
