//
//  PullRequestsListViewController.swift
//  GithubRepositories
//
//  Created by Junior Silva on 21/07/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PullRequestsListDisplayLogic: class {
    func reloadTable()
}

class PullRequestsListViewController: UIViewController {
    
    @IBOutlet weak var tableView: UITableView!
    
    var interactor: PullRequestsListBusinessLogic?
    var router: (NSObjectProtocol & PullRequestsListRoutingLogic & PullRequestsListDataPassing)?

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    private func setup() {
        let viewController = self
        let interactor = PullRequestsListInteractor()
        let presenter = PullRequestsListPresenter()
        let router = PullRequestsListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
        interactor?.fetchPullRequestsList()
    }
    
    private func setupTableView() {
        tableView.delegate = self
        tableView.dataSource = self
        tableView.separatorStyle = .none
        tableView.register(PullRequestListTableViewCell.self, forCellReuseIdentifier: PullRequestListTableViewCell.identifier)
    }

}

extension PullRequestsListViewController: PullRequestsListDisplayLogic {
    
    func reloadTable() {
        tableView.reloadData()
    }

}

// MARK TABLEVIEW DELEGATE AND DATASOURCE
extension PullRequestsListViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        interactor?.didSelectRow(at: indexPath.row)
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return interactor?.numberOfRows ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: PullRequestListTableViewCell.identifier) as? PullRequestListTableViewCell,
            let viewModel = interactor?.cellForRow(at: indexPath.row) else { return UITableViewCell() }
        
        cell.configure(viewModel)
        cell.accessibilityLabel = "Pull Requests"
        
        return cell
    }
    
}
