//
//  PullRequestsListInteractor.swift
//  GithubRepositories
//
//  Created by Junior Silva on 21/07/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol PullRequestsListBusinessLogic {
    func doSomething(request: PullRequestsList.Something.Request)
}

protocol PullRequestsListDataStore {
    //var name: String { get set }
}

class PullRequestsListInteractor: PullRequestsListBusinessLogic, PullRequestsListDataStore {
    var presenter: PullRequestsListPresentationLogic?
    var worker: PullRequestsListWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: PullRequestsList.Something.Request) {
        worker = PullRequestsListWorker()
        worker?.doSomeWork()

        let response = PullRequestsList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
