//
//  RepositoriesListInteractor.swift
//  GithubRepositories
//
//  Created by Junior Silva on 21/07/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol RepositoriesListBusinessLogic {
    func loadRepositoriesList()
}

protocol RepositoriesListDataStore {
    //var name: String { get set }
}

class RepositoriesListInteractor: RepositoriesListBusinessLogic, RepositoriesListDataStore {
    var presenter: RepositoriesListPresentationLogic?
    var worker: RepositoriesListWorker?
    
    init(worker: RepositoriesListWorker = RepositoriesListWorker()) {
        self.worker = worker
    }
    
    func loadRepositoriesList() {
        worker?.searchRepositoriesList(page: 1).done(handleSuccess).catch(handleError)
    }
    
    private func handleSuccess(_ response: RepositoriesList.Response) {
        print(response)
    }
    
    private func handleError(_ error: Error) {
        
    }
}
