//
//  RepositoriesListRouter.swift
//  GithubRepositories
//
//  Created by Junior Silva on 21/07/20.
//  Copyright (c) 2020 Junior Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RepositoriesListRoutingLogic {
    func routeToPullRequestsList()
}

protocol RepositoriesListDataPassing {
    var dataStore: RepositoriesListDataStore? { get }
}

class RepositoriesListRouter: NSObject, RepositoriesListRoutingLogic, RepositoriesListDataPassing {
    weak var viewController: RepositoriesListViewController?
    var dataStore: RepositoriesListDataStore?

    func routeToPullRequestsList() {
        let destinationVC = PullRequestsListViewController()
        var destinationDataStore = destinationVC.router?.dataStore
        passDataToPullRequestsList(source: dataStore, destination: &destinationDataStore)
        //viewController?.navigationController?.pushViewController(destinationVC, animated: true)
        viewController?.present(destinationVC, animated: true)
    }
    
    func passDataToPullRequestsList(source: RepositoriesListDataStore?, destination: inout PullRequestsListDataStore?) {
        guard let source = source, var destination = destination else { return }
        destination.repository = source.repository
    }
}
